### ISSUE TITLE
Second build in Gradle Daemon mode (2.4+) gives "engine 'memory' was not found" error

### ISSUE THREAD

**Issue by msgilligan** [jbake-org/jbake-gradle-plugin#14]
The full error is:

```
Execution failed for task ':jbake'.
 > Error on opening database: the engine 'memory' was not found. URL was: memory:cache. Registered engines are: []
```

I'm seeing this intermittently (but more than half the time.) I've search documentation and googled for the error and can't figure out what I'm doing wrong. At the very least it's not a very helpful error message.

I can provide my `build.gradle` or my complete project if necessary.

One more clue: It seems to _always_ work immediately after I change the version of a dependency in `build.grade` but if a do a `rm -rf build` and then rerun `gradle jbake` I get the error again.

**Comment by msgilligan** [comment]
This may be related to https://discuss.gradle.org/t/problem-building-jbake-project-with-gradle-2-4/ - although in my case `clearCache = true` does not seem to fix it. 

Stopping the Gradle Daemon and rerunning the build *does* seem to fix it.

**Comment by jonbullock** [comment]
My experience of Gradle is extremely limited, however a bug has been raised for JBake v2.4.0 about the incremental rendering being broken which may be related... do you have the same issue when using JBake v2.3.2?

**Comment by msgilligan** [comment]
I saw the problem with both 2.3.2 and 2.4.0 as I mentioned here: https://github.com/jbake-org/jbake-gradle-plugin/issues/15

**Comment by ancho** [comment]
Try to use my unofficial release of 0.2.1 and let me know if the error still exists.
See https://github.com/jbake-org/jbake-gradle-plugin/issues/9#issuecomment-73418953 for an example configuration.

**Comment by jdigger** [comment]
Another work-around is to use the `--no-daemon` flag when building, though of course that's quite a bit slower.

The fundamental issue is the use of a static lifecycle call, specifically [`Orient.instance().shutdown();` in Oven.bake()](https://github.com/jbake-org/jbake/blob/v2.4.0/src/main/java/org/jbake/app/Oven.java#L227). The reason why it's a problem is that the classloader that the `Orient.instance()` is a part of is the Gradle daemon classloader. (Since it's a plugin, it's loading in the same context as the main Gradle classes for that build file.)

Changing the version -- or any non-trivial information about the build -- causes Gradle to tosses the old daemon. (Since it needs to recompile the build file, having the daemon "hot loaded" doesn't help.)

The right way to handle this kind of thing is to either explicitly control creation and destrunction of resources in your application's context (e.g., at the start and end of `bake()`), or let the runtime handle it for you.

Fortunately there's no need to exlicitly call `Orient.instance().shutdown()` because the developers of OrientDB are making proper use of the JVM's runtime: In `Orient.startup()` they create a `OrientShutdownHook` which registers itself with `Runtime.getRuntime().addShutdownHook(this)`. So before the JVM shuts down it will "do the right thing" and release the resources.

In jbake-org/jbake@4e9285f3bddf0203231a3b55c13d7f9ffcb87318 the offending line was commented out as part of providing "watch" support (which would be using classloaders in a similar way to the Gradle daemon) and has been merged to master, so the good news is that whenever v2.5 comes out this will be fixed.

**Comment by jdigger** [comment]
For what it's worth, I upgraded my local installation to use JBake 2.5.0-SNAPSHOT and this bug no longer manifests.
