### ISSUE TITLE
Instructions in README don't match released version

### ISSUE THREAD

**Issue by msgilligan** [jbake-org/jbake-gradle-plugin#16]
The instructions in the README don't match the released _version 0.2_. They don't even match the version number used in the README which is also _version 0.2_.

For example the instructions say to use `srcDirName`  to change the JBake source directory from the default, but in version 0.2 the correct way to do this is with `input`, for example:

```
jbake {
    input = file("$projectDir")
}
```

Either documentation should be published somewhere for currently released versions or the README should have seperate sections for stable and snapshot versions. At the very least the README should have a _note_ or _warning_ and use the matching snapshot version in the `buildscript` classpath configuration.

**Comment by abhijitsarkar** [comment]
Yeah, the only thing right about the README is that it's a markdown file.
Do you've an example project that I could refer to while I go through the frustrating process of following misleading documentation?

**Comment by jonbullock** [comment]
You mean like the example sites that use the plugin listed in the README...?
​
Oh and the file is is an AsciiDoc formatted file ;-)

**Comment by abhijitsarkar** [comment]
@jonbullock No I mean that:

- The README, the AsciiDoc formatted file, is straight up wrong. SNAPSHOT version is not supported by the Gradle plugin center so the following block could never have worked.
```
plugins {
    id 'me.champeau.jbake' version '0.3.0-SNAPSHOT'
}
```

- Removing the SNAPSHOT doesn't work either because the last released version is 0.2. https://plugins.gradle.org/plugin/me.champeau.jbake

- Samples? Each one uses a different version of the plugin with a different configuration. One uses v 0.1, another v 0.2, none 0.3.

- The README, the AsciiDoc formatted file, again shows the following block that doesn't compile when put in a build file using v 0.2:
```
jbake {
    pegdownVersion = '1.4.2'
    freemarkerVersion = '2.3.19'
    asciidoctorJavaIntegrationVersion = '0.1.4'
    asciidoctorjVersion = '1.5.4'
}
```

I stopped after I found the above issues, so there may be more that I didn't find.

**Comment by mperry** [comment]
I will have a look at this this week.  Not sure what the status of the plugin is at the moment.

**Comment by ancho** [comment]
It is time for a release. And a little love to the Readme. I screwed it up, more or less, back in the days while working on the configurable version support. Unfortunately a release of 0.2.1 has never happened officially which is the cause for the irritation. People are using my published version already. See #9
